### ISSUE TITLE
Is the readme up-to-date?

### ISSUE THREAD

**Issue by blg002** [contentful/extensions#13]
I'm slightly confused by the…

> Navigate into the extension folder
> `cd examples/wistia`

bit. When i clone `ui-extensions-sdk.git` there is no "examples" dir.

**Comment by hlabas** [comment]
Indeed, thanks for noticing. We recently migrated samples to this repository and it seems some of them have remaining typos.
We'll fix that soon and will keep you posted.
Best
Hervé

**Comment by hlabas** [comment]
We just updated the documentation which should fix the issues.
