### ISSUE TITLE
bynder-assets extension throws error when trying to open the dialog

### ISSUE THREAD

**Issue by ThomasJacobsWK** [contentful/extensions#149]
Hi,

I attempted to create a custom field in Contentful using the bynder-assets extension which I installed through the marketplace (https://www.contentful.com/developers/marketplace/bynder-assets/).

Unfortunately I get the following error in console when I try to press the “Select images in Bynder” button:

> Field.js:41 
> Uncaught (in promise) 
> {code: "Error", message: "no extension found", data: undefined}
> code: "Error"
> data: undefined
> message: "no extension found"

I believe I entered a correct Bynder URL in the widget config form (“companyname.getbynder.com”), though I tried out variations as well.

Any tips on what is causing this and how to fix it?

Thanks in advance.

**Comment by suevalov** [comment]
Hey @ThomasJacobsWK! Thanks for letting us know. We've rolled out a fix today. Can you verify that it works for you?

**Comment by ThomasJacobsAppno** [comment]
@suevalov : I just tested this again and it seems to be working correctly (in the UI at least). Thanks for the fix.

**Comment by suevalov** [comment]
Fixed by #151
