### ISSUE TITLE
Bynder assets extension breaks the translation fallback system

### ISSUE THREAD

**Issue by zuuperman** [contentful/extensions#154]
There is currently an issue with the way the Bynder assets plugin is storing the values. The plugin already stores an empty array, even if no image was selected.

This breaks the fallback system, as Contentful thinks that the image is translated.

You can see the issue in the screenshot. When we now perform a graphql query for this entry, we receive an empty array instead of the default language's picture.

<img width="884" alt="Screenshot 2019-07-02 at 15 29 33" src="https://user-images.githubusercontent.com/1125693/60516935-0fe7cb80-9cdf-11e9-9f9d-782377ef1ece.png">

**Comment by zuuperman** [comment]
I created a pull request at https://github.com/contentful/extensions/pull/155

**Comment by suevalov** [comment]
Closed by #155
