### ISSUE TITLE
Cloudinary UI extension doesn't work in Safari

### ISSUE THREAD

**Issue by skikirkwood** [contentful/extensions#167]
In Safari and Firefox the Cloudinary UI extension button pops up a modal and asks you to log in to Cloudinary, and attempting to do so hangs. In Chrome it works perfectly.

**Comment by Servitours** [comment]
Yes I'm facing the same issue.
When trying to log in by clicking the link, a new tab opens in Safari with the text "Redirecting to Media Library..." and that's it.

It works well in Chrome and Firefox though.
