### ISSUE TITLE
Bynder extension - thumbnail src seems to be broken

### ISSUE THREAD

**Issue by pauloamgomes** [contentful/extensions#187]
Seems that latest changes are causing all Bynder objects to be broken:

![image](https://user-images.githubusercontent.com/102261/63511438-22a9a000-c4d9-11e9-8a93-df951f3690b1.png)

However can still fetch the `id` and `src` from the field using the API.

If I remove the image and select a new one can see the thumbnail updating in contentful, but the attribute `src` is lost, I have access to a few new attributes (including thumbnails) but not the `src` one.

Thanks in advance

**Comment by jelz** [comment]
Hi @pauloamgomes, I've just shipped a change that should fix this issue.

Could you please get back to me if it's fixed for you?

**Comment by pauloamgomes** [comment]
Hi @jelz , thanks for the response.
We decided to update all Bynder images as a workaround, in such case can see you have now a fallback to resource.src and that probably solves the issue.
