### ISSUE TITLE
Links to css and js related files for Alloy Editor are broken

### ISSUE THREAD

**Issue by burdenyuk** [contentful/extensions#2]
Hello Contentful,

First of all thank you very much for Contentful system and recent updates for UI extensions API!

I want to install Alloy Editor UI extension and was leading the instructions from https://www.contentful.com/r/knowledgebase/ui-extensions-guide/ and got a problem:

On the paragraph 'Building an editor extension' there is an html file example with lines:

    <link href="https://contentful.github.io/extensions-samples/libs/alloy-editor/assets/alloy-editor-ocean-min.css" rel="stylesheet">
    <script src="https://contentful.github.io/extensions-samples/libs/alloy-editor/alloy-editor-all-min.js"></script>

Those 2 links above are broken: https://contentful.github.io/extensions-samples/libs/alloy-editor/assets/alloy-editor-ocean-min.css and https://contentful.github.io/extensions-samples/libs/alloy-editor/alloy-editor-all-min.js

Thanks in advance!

Best regards,
Denys

**Comment by hlabas** [comment]
Thanks for pointing this out!
We've just pushed a fix.

**Comment by burdenyuk** [comment]
Thank you very much for quick fixes!
