### ISSUE TITLE
Wistia Example - displaying embeds inside an iFrame

### ISSUE THREAD

**Issue by joshRpowell** [contentful/extensions#20]
Thanks for putting this together to share some cool features!  I got the Wisitia extension installed in my Contentful Space.  However, I'm running into an issue displaying the embeds inside an iFrame. 

![replacing income 2017-06-05 10-25-27](https://cloud.githubusercontent.com/assets/6732638/26787901/86c3a11c-49d9-11e7-8284-ae67d13f2c05.png)

the same video displays fine using the URL field type when I have the domain restriction enabled for `contentful.com`: 
![replacing income 2017-06-05 10-28-36](https://cloud.githubusercontent.com/assets/6732638/26788060/00fcf6f4-49da-11e7-8eea-f53d84b89c87.png)

I reached out to Wistia support and they shared the following: 
```
If Contentful is sandboxing those embeds inside an iFrame, it's going to prevent the use of Domain Restrictions in that environment. Sandboxing prevents our scripts from properly identifying the referrer URL - if you disable Domain Restrictions, do you see a missing fullscreen control on those embeds? That would be another symptom of sandboxing the embeds in this fashion (because iFrame elements need the allowfullscreen property for that control to be available - this is true for all iFrames around a given embed).
```
I disabled Domain Restrictions temporarily and this did not see a missing fullscreen control on those embeds.

Any suggestions on modifying the extension in order to work with Domain Restrictions?

**Comment by joshRpowell** [comment]
additional feedback from Wistia: 
```
I do notice that the extension has largely not been updated in 11mos, and the screenshots displayed there have our old player which was deprecated back in July of 2016. The embeds in the screenshot also are missing the fullscreen control, which is a possible red flag indicating the "sandboxing" issue I mentioned before. 
```

**Comment by RHarper508** [comment]
Hey there! Harper from Wistia support, I've been working with @joshRpowell on this one. I'm noticing that this widget wraps everything in an iFrame. I would recommend including our `E-v1.js` script inside the parent iFrame - it's currently included with each embed, but it needs to be inside each parent iFrame for certain on-page functionality to work:
`<script src="https://fast.wistia.net/assets/external/E-v1.js" async></script>`

You may also want to include that in the iFrame's srcdoc to be on the safe side. Sandboxing our embeds adds a lot of complications for certain player functionality.

Also, I'd recommend adding the `allowfullscreen `property to the parent iFrame as well.

**Comment by geigerzaehler** [comment]
Thanks for letting us know. We will investigate how to fix the sandboxing issue.

**Comment by joshRpowell** [comment]
@geigerzaehler any update?

**Comment by joshRpowell** [comment]
@geigerzaehler any update?  
curious if extensions going to get continued support? 
if so, should the wistia example be removed until fixed?

**Comment by geigerzaehler** [comment]
It does not seem possible to run Wistia in a sandboxed iframe without placing a script in the parent window. For that reason we are going to remove this extension from the samples.
