### ISSUE TITLE
Question: Shopify Extension, Selecting Multiple Products

### ISSUE THREAD

**Issue by robmellett** [contentful/extensions#209]
Hey there,

Thanks for the great work with the Shopify extension.  
https://www.contentful.com/developers/marketplace/contentful-ui-shopify/

I've installed the plugin and got it working within Contentful, I was just wondering how to select multiple products?

It appears I can only select one at a time?  Am I missing something obvious?

![image](https://user-images.githubusercontent.com/26024074/65114799-8cf72700-da2a-11e9-9c5b-77579f6e3a39.png)

Thanks in advanced,

**Comment by Jwhiles** [comment]
This may be related to the content type you are using the app with. You'll need to use a Symbol List field in order to select multiple products.
