### ISSUE TITLE
Add shortcode-like functionality to the Markdown editor

### ISSUE THREAD

**Issue by sandrarobotos** [contentful/extensions#22]
It would be great if the Markdown editor had something similar to shortcodes in WordPress. We want to enable our content editors to add formatted content inside the body of a blog post. For example, adding an image that has a caption in whatever order they want.

I know the markdown editor supports HTML, but our editors don't know HTML so they can't do that. Nor would we want them too.

Another use could be giving them an easy way to add abbreviations for better accessibility, for example, so they could enter something like 
`[abbriviation description="Thank God It's Friday"]TGIF[abbreviation]` 
and it would be parsed into the proper HTML markup.

**Comment by jessepinho** [comment]
FWIW, I've been using the following syntax for shortcodes: `<!--[ ShortcodeName arg1="val1" ]-->`. Of course, the Markdown editor doesn't actually render this. But wrapping it in an HTML comment ensures that it will never appear raw if, for some reason, my frontend shortcode renderer is failing.
