### ISSUE TITLE
Auto generated slug does not work on existing items

### ISSUE THREAD

**Issue by T04435** [contentful/extensions#286]
I have followed this [tutorial](https://www.contentful.com/blog/2019/11/29/creating-automated-slug-with-contentful/) to add a slug to one of my content types.

I found that the slug is not generated on any of the already existing content entries. While it does work on the new entries of the same content type.

Is this a bug or there is a migration process to generate slugs on existing entries?

existing entry:
![image](https://user-images.githubusercontent.com/10654469/75094363-73ac6500-55de-11ea-8521-749ff6d76020.png)

new entry 
![image](https://user-images.githubusercontent.com/10654469/75094408-d867bf80-55de-11ea-8916-b776fc27bca0.png)

Content Model:
![image](https://user-images.githubusercontent.com/10654469/75094383-9b033200-55de-11ea-8392-d0d1d898b93d.png)

Thanks.

**Comment by Jwhiles** [comment]
Closing this issue, as it doesn't seem to be related to this repository extensions. If this is still an issue, please use our support channel https://www.contentful.com/support/
