### ISSUE TITLE
MUX video uploader is no longer in Contentful Marketplace

### ISSUE THREAD

**Issue by dsmikeyorke** [contentful/extensions#291]
Hi all, I tried installing MUX video uploader like I had done in the past through [Contentful Marketplace](https://www.contentful.com/marketplace/) but noticed it has been removed.  I was able to install it using the directions listed on git but it seems like that version is not the same as the version installed through the marketplace.  

Will MUX video uploader be returning to Contentful Marketplace?

**Comment by dsmikeyorke** [comment]
I've managed to get the current version installed by following the "Install via the Contentful interface
" instructions but changing the path to:
https://github.com/contentful/extensions/blob/master/marketplace/mux-video-uploader/extension.json

instead of:
https://github.com/muxinc/examples/blob/master/contentful-uploader/extension.json

**Comment by realityking** [comment]
Hi @dsmikeyorke,

Sorry for the long delay in getting back to you. The Mux integration was caught up in the migration to our new Marketplace and Apps. This is now fixed and Mux has been back in the Marketplace for several weeks. You can find the app here: https://www.contentful.com/marketplace/app/mux/
