### ISSUE TITLE
Installing extension from Github fails

### ISSUE THREAD

**Issue by mlojko** [contentful/extensions#312]
Trying to install the extension, using the following URL for extension.json:
https://github.com/contentful/extensions/blob/master/samples/content-tree/extension.json

Fails with the following error
Could not fetch the descriptor file. Please check the URL and try again.
![image](https://user-images.githubusercontent.com/22581618/82497294-05cbe880-9abc-11ea-9030-fc2a6d389ecd.png)

Thanks,
Martin

**Comment by landtco** [comment]
Same issue, did you had the chance to solve it @mlojko ?

**Comment by Jwhiles** [comment]
This should now work :)
