### ISSUE TITLE
Conditional Logic extension

### ISSUE THREAD

**Issue by TheMangoTrain** [contentful/extensions#340]
Hi,

I'd like to add conditional logic to a specific Contentful content model. The logic would start from radio buttons, where the user would make a selection, and different form content would appear according to their selection. Something along the lines of:

```
<bunch of other fields>
...
<a selection field (e.g. radio button>
If A, show fields 1,3,4
If B, show fields 3,5,2
If C, show fields 6,1,4
...
<bunch of other fields>
```

From what I understand, building a custom UI extension is the key.

**QUESTION:** Do we have to re-create the entire content entry form in the UI extension (the `<bunch of other fields>`), just to achieve our desired conditional logic in one specific place?

In early exploration of sample code, this seems like the case. Can we avoid this? I haven't seen an explicit statement one way or another.

**Comment by Jwhiles** [comment]
Hey @TheMangoTrain - sorry for the slow reply.

Probably the best way to achieve this would to create a custom entry editor. If this is something you would want to do, I recommend using our [field editors](https://github.com/contentful/field-editors) repo - as this would allow you to avoid re-implementing the various different field editors.
