### ISSUE TITLE
Alloy editor documentation clarification (make create)

### ISSUE THREAD

**Issue by christineywang** [contentful/extensions#36]
For the [Alloy editor](https://github.com/contentful/extensions/tree/master/samples/alloy-editor) extension, the command `make create` uploads AND serves the UI extension (so the user doesn't need to type in `make serve` as per the docs).

Also, the extension is uploaded directly to Contentful's server so it is never hosted in the local environment. Therefore, mention of `make update-force` may be confusing and unnecessary.  

Should we change the documentation? I can create a PR if you agree with this assessment.

**Comment by floelhoeffel** [comment]
Hey @christineywang that would be great. AFAIK forcing only makes sense if you upload the extension to Contentful though..

**Comment by christineywang** [comment]
Sorry for the delay. Will submit a PR today!

**Comment by jelz** [comment]
`make` step is not needed anymore for this extension.
