### ISSUE TITLE
Inbound References example links to 404 page

### ISSUE THREAD

**Issue by christineywang** [contentful/extensions#56]
The link for the inbound references extension does not work (maybe the repo is private):
https://github.com/contentful/extensions/blob/master/samples/inbound-references

I have a user who would like to see a sidebar UI extension example--is there a way you could make this public?

**Comment by floelhoeffel** [comment]
Good catch - I removed the link from the readme. Did you find the link somewhere else?

**Comment by unrealmaker** [comment]
I also need an example for a sidebar UI extension. Where can I find it?

**Comment by floelhoeffel** [comment]
Currently we dont have one. You could have a look at the inbound-references one re removed:

https://github.com/contentful/extensions/commit/6c523873e683336f48e7637ab4167cb35069e5e5

Please update the SDK version you are using to v3

**Comment by unrealmaker** [comment]
Ok. 
Just to make sure since I will use this in production: in the GIT commit (6c52387) it says: "Removed inbound example as this is now a web app feature" - what does this really mean? Will this feature be removed in the future?

Thanks.

**Comment by floelhoeffel** [comment]
We removed that particular UI Extension because the Contentful web app now shows inbound references on every entry. Hence no need to custom add that through a UI extension. The possibility to render UI Extensions in the sidebar is going to stay.
