### ISSUE TITLE
Can the slug generator correctly process "folder paths"?

### ISSUE THREAD

**Issue by atav32** [contentful/extensions#59]
For example, will `folder/page-name` correctly configure a url, `www.my-site.com/folder/page-name` or will it just break?

**Comment by floelhoeffel** [comment]
I am not sure I understand the question. Basically the extension allows you to customize the how a slug is generated based on e.g. the entry title. Final URLs / routing needs to be handled in your client's code.

Does that help?

**Comment by atav32** [comment]
Yeah this is probably not the right place to ask this question. I'll ask it on the discourse forum.
