### ISSUE TITLE
Slug Gen docs don't explain the extention

### ISSUE THREAD

**Issue by emilbruckner** [contentful/extensions#63]
I added the slug generator to a project a couple of months ago and had no problems, added it to another one today, and this happened:

![image](https://user-images.githubusercontent.com/9105589/42343269-d8481b98-8098-11e8-83ea-7c3690b0121a.png)

The slug won't generate and all three icons show up in it.
I read this error: `Cannot read property 'onValueChanged' of undefined`

The problem is in this line of the plugin:
```javascript
var titleField = api.entry.fields.title
```

The generator assumes that the title is the field with field-id `title`. Wasn't the case for this project. 

### How to solve:
Either
1) Get the title from the entry title, not the field `title`
2) Update the README

**Comment by suevalov** [comment]
Solved by #83
