### ISSUE TITLE
Ordered and Unordered List Buttons for Alloy Editor Toolbar

### ISSUE THREAD

**Issue by jsfowles** [contentful/extensions#64]
Not sure if this is a duplicate of #49 but it would be nice to have the option to create a list from the toolbar.

The current toolbar is limited to the following: 
<img width="355" alt="screen shot 2018-07-16 at 4 46 43 pm" src="https://user-images.githubusercontent.com/17182194/42787462-d949d54a-8917-11e8-919d-a8134d3d5703.png">

A more robust one such as this would be great:

<img width="353" alt="screen shot 2018-07-16 at 4 49 15 pm" src="https://user-images.githubusercontent.com/17182194/42787553-33d74ede-8918-11e8-828a-448b032527a1.png">

**Comment by floelhoeffel** [comment]
Hey @jsfowles - that should be very easy by changing the configuration: https://alloyeditor.com/docs/features/ul.html

We are very happy about a PR if you would like to share the ❤️ :)

Thanks!
