### ISSUE TITLE
Use custom extension to retrieve Contentful media assets

### ISSUE THREAD

**Issue by gmarraro-ellevest** [contentful/extensions#65]
I build a custom WYSIWYG text editor with [Froala](https://github.com/froala/react-froala-wysiwyg) and hooked it up into my Contentful space successfully. However, there is an insert image button in my editor that I want to use to retrieve assets from the media I have hosted on Contentful, as it functions in the built-in text module ("Insert Media") that Contentful provides: 

<img width="696" alt="screen shot 2018-08-06 at 10 06 44 am" src="https://user-images.githubusercontent.com/39923835/43721380-9d27d00e-9960-11e8-86cb-624354c16ab6.png">

<img width="751" alt="screen shot 2018-08-06 at 10 10 08 am" src="https://user-images.githubusercontent.com/39923835/43721492-ed4e58be-9960-11e8-8667-86509823312a.png">

Does Contentful have a way to insert the same functionality into outside custom extensions? I assume there is already code that exists for this purpose, since it is already a feature that exists.

**Comment by floelhoeffel** [comment]
That should be possible using https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#selecting-a-single-asset
