### ISSUE TITLE
Sidebar-only extensions?

### ISSUE THREAD

**Issue by jessepinho** [contentful/extensions#66]
I guess this is a feature request. It'd be nice to be able to have sidebar-only extensions — i.e., extensions that are not tied to a specific field. 

I want to create a UI extension that generates a code snippet for our publishing team to copy/paste. The snippet will include auto-generated tracking links that include the entry title and other fields. This extension should live in the Contentful sidebar.

However, the only way to include this extension is to create a new field that uses the extension, even if that field isn't needed for anything. For example, the [Contentful URL checker UI extension](https://github.com/stefanjudis/contentful-link-checker-ui-extension) requires that you add a Boolean field to your content model, even though that field won't be used for anything.

So, would it be possible to make UI extensions that are not tied to a field, live in the sidebar, and have access to the entry being edited?

Thanks!

EDIT: I noticed that [the SDK docs](https://github.com/contentful/ui-extensions-sdk#content-management-extensions) mention entry-level extensions that just live in the sidebar. This is basically what I'm referring to — but I don't see any way to make those without tying them to a specific field...?

**Comment by suevalov** [comment]
Hi @jessepinho! Thanks for the feature request. 

We'll work on that. The way it works now is a quite hacky, all people agree with that :)

**Comment by jessepinho** [comment]
Future Googlers: see https://www.contentful.com/developers/docs/extensibility/custom-sidebar/
