### ISSUE TITLE
Bynder Sample Extension - Cannot load application in sandboxed iframe

### ISSUE THREAD

**Issue by michaellippmann** [contentful/extensions#77]
Hi,
I have tried installing the newly created Bynder sample extension (very happy to see it here,) except there seems to be an issue executing the Bynder client js file, due to iframe sandboxing.

It looks like the client file is trying to read from sessionStorage but is being blocked by the browser due to it coming from a different origin.

Wondering if you have seen this issue during development?

> Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.

**Comment by floelhoeffel** [comment]
@michaellippmann you need to host the extension using the 'src' property. When using `srcdoc` the extension will not work due to more strict iframe policy.

Feel free to re-open if this doesnt solve it.
