### ISSUE TITLE
JSON Form Editor doesn't seem to work

### ISSUE THREAD

**Issue by mrcthms** [contentful/extensions#78]
Hi there 👋 ,

I've been reading up on customsing the Contentful UI via the Extensions SDK, and I installed the JSON Form Editor, and used it on a field in a content type just to test it out, but when I started to create content it didn't work as expected, and errored in the console (see screenshot below)

<img width="1637" alt="screenshot 2018-11-09 12 23 03" src="https://user-images.githubusercontent.com/2562596/48262454-7cdde680-e41a-11e8-9ca0-d6a17b70b460.png">

If my understanding of this example is correct, an individual should take this boilerplate and make their own extensions with their own schemas, but I thought I'd just highlight this potential issue in the boilerplate.

Thanks!

**Comment by stefanjudis** [comment]
I believe this should be fixed thanks to @Folashade . :)

https://github.com/contentful/extensions/pull/80

Closing here – happy to reopen if that's still an issue.
